package com.team.summs_backend.dto;

import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class EfficiencyMetricsResponse {
  /** Average revenue per completed rental. */
  private BigDecimal averageRevenuePerRental;

  /** Average revenue per car rental. */
  private BigDecimal averageCarRentalRevenue;

  /** Average revenue per bike rental. */
  private BigDecimal averageBikeRentalRevenue;

  /** Average revenue per scooter rental. */
  private BigDecimal averageScooterRentalRevenue;

  /** Total revenue divided by total vehicles in fleet. */
  private BigDecimal revenuePerVehicle;

  /** Average number of rentals per vehicle (completed rentals / total vehicles). */
  private double averageRentalFrequencyPerVehicle;

  /** Percentage of revenue generated by cars. */
  private double carRevenuePercentage;

  /** Percentage of revenue generated by bikes. */
  private double bikeRevenuePercentage;

  /** Percentage of revenue generated by scooters. */
  private double scooterRevenuePercentage;
}
